b' <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1">  <meta name="description" content="www.paste.org - allows users to paste snippets of text, usually samples of source code, for public viewing."> <meta name="author" content="An Australian"> <link rel="icon" href="/favicon.ico"> <title>Paste code - paste.org</title>  <link href="/assets/themes/bleh/css/github-highlight.css" rel="stylesheet"> <script src="/assets/themes/bleh/js/highlight.pack.js"></script> <script>hljs.initHighlightingOnLoad();</script> </head> <body> <p><pre><code class="nohighlight">2011-08-29 00:57:40 INFO ZServer HTTP server started at Mon Aug 29 00:57:40 2011\n        Hostname: 0.0.0.0\n        Port: 8080\n2011-08-29 00:57:40 INFO Zope Set effective user to &quot;daniel&quot;\n2011-08-29 00:58:04 INFO ZEO.ClientStorage zeostorage ClientStorage (pid=7196) created RW/normal for storage: \'1\'\n2011-08-29 00:58:04 INFO ZEO.cache created temporary cache file \'&lt;fdopen&gt;\'\n2011-08-29 00:58:05 INFO ZEO.zrpc.Connection(C) (127.0.0.1:8100) received handshake \'Z3101\'\n2011-08-29 00:58:05 INFO ZEO.ClientStorage zeostorage Testing connection &lt;ManagedClientConnection (\'127.0.0.1\', 8100)&gt;\n2011-08-29 00:58:06 INFO ZEO.ClientStorage zeostorage Server authentication protocol None\n2011-08-29 00:58:06 INFO ZEO.ClientStorage zeostorage Connected to storage: (\'localhost\', 8100)\n2011-08-29 00:58:06 INFO ZEO.ClientStorage zeostorage No verification necessary -- empty cache\n2011-08-29 00:59:05 INFO Zope Ready to handle requests\n2011-08-29 00:59:07 WARNING OFS.Uninstalled Could not import class \'IntIds\' from module \'five.intid.intid\'\n2011-08-29 00:59:07 WARNING OFS.Uninstalled Could not import class \'RelationCatalog\' from module \'z3c.relationfield.index\'\n2011-08-29 00:59:07 WARNING OFS.Uninstalled Could not import class \'ICatalog\' from module \'zc.relation.interfaces\'\n2011-08-29 00:59:07 WARNING OFS.Uninstalled Could not import class \'IIntIds\' from module \'zope.intid.interfaces\'\n2011-08-29 00:59:07 WARNING OFS.Uninstalled Could not import class \'IDexterityFTI\' from module \'plone.dexterity.interfaces\'\n2011-08-29 00:59:07 WARNING OFS.Uninstalled Could not import class \'DexterityFactory\' from module \'plone.dexterity.factory\'\n2011-08-29 00:59:08 WARNING OFS.Uninstalled Could not import class \'DexterityFTI\' from module \'plone.dexterity.fti\'\n2011-08-29 00:59:08 ERROR ZODB.Connection Couldn\'t load state for 0x06a9\nTraceback (most recent call last):\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 860, in setstate\n    self._setstate(obj)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 914, in _setstate\n    self._reader.setGhostState(obj, p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/serialize.py&quot;, line 613, in setGhostState\n    obj.__setstate__(state)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.component-3.9.5-py2.6.egg/zope/component/persistentregistry.py&quot;, line 40, in __setstate__\n    self._createLookup()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 89, in _createLookup\n    self._v_lookup = self.LookupClass(self)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 437, in __init__\n    self.init_extendors()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 474, in init_extendors\n    self.add_extendor(p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 478, in add_extendor\n    for i in provided.__iro__:\nAttributeError: type object \'ICatalog\' has no attribute \'__iro__\'\n2011-08-29 00:59:08 ERROR Zope.SiteErrorLog 1314572348.470.672714579596 http://www.danieltordable.es/danieltordable.es\nTraceback (innermost last):\n  Module ZPublisher.Publish, line 115, in publish\n  Module ZPublisher.BaseRequest, line 437, in traverse\n  Module ZPublisher.BeforeTraverse, line 97, in __call__\n  Module Products.CMFCore.PortalObject, line 78, in __before_publishing_traverse__\n  Module zope.event, line 23, in notify\n  Module zope.component.event, line 24, in dispatch\n  Module zope.component._api, line 136, in subscribers\n  Module zope.component.registry, line 321, in subscribers\n  Module zope.interface.adapter, line 583, in subscribers\n  Module zope.component.event, line 32, in objectEventNotify\n  Module zope.component._api, line 136, in subscribers\n  Module zope.component.registry, line 321, in subscribers\n  Module zope.interface.adapter, line 583, in subscribers\n  Module plone.browserlayer.layer, line 15, in mark_layer\n  Module zope.component._api, line 179, in getAllUtilitiesRegisteredFor\n  Module zope.component.registry, line 176, in getAllUtilitiesRegisteredFor\n  Module ZODB.Connection, line 860, in setstate\n  Module ZODB.Connection, line 914, in _setstate\n  Module ZODB.serialize, line 613, in setGhostState\n  Module zope.component.persistentregistry, line 40, in __setstate__\n  Module zope.interface.adapter, line 89, in _createLookup\n  Module zope.interface.adapter, line 437, in __init__\n  Module zope.interface.adapter, line 474, in init_extendors\n  Module zope.interface.adapter, line 478, in add_extendor\nAttributeError: type object \'ICatalog\' has no attribute \'__iro__\'\n2011-08-29 00:59:09 ERROR ZODB.Connection Couldn\'t load state for 0x06a9\nTraceback (most recent call last):\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 860, in setstate\n    self._setstate(obj)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 914, in _setstate\n    self._reader.setGhostState(obj, p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/serialize.py&quot;, line 613, in setGhostState\n    obj.__setstate__(state)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.component-3.9.5-py2.6.egg/zope/component/persistentregistry.py&quot;, line 40, in __setstate__\n    self._createLookup()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 89, in _createLookup\n    self._v_lookup = self.LookupClass(self)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 437, in __init__\n    self.init_extendors()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 474, in init_extendors\n    self.add_extendor(p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 478, in add_extendor\n    for i in provided.__iro__:\nAttributeError: type object \'IIntIds\' has no attribute \'__iro__\'\n2011-08-29 00:59:09 ERROR ZODB.Connection Couldn\'t load state for 0x06a9\nTraceback (most recent call last):\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 860, in setstate\n    self._setstate(obj)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 914, in _setstate\n    self._reader.setGhostState(obj, p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/serialize.py&quot;, line 613, in setGhostState\n    obj.__setstate__(state)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.component-3.9.5-py2.6.egg/zope/component/persistentregistry.py&quot;, line 40, in __setstate__\n    self._createLookup()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 89, in _createLookup\n    self._v_lookup = self.LookupClass(self)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 437, in __init__\n    self.init_extendors()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 474, in init_extendors\n    self.add_extendor(p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 478, in add_extendor\n    for i in provided.__iro__:\nAttributeError: type object \'IIntIds\' has no attribute \'__iro__\'\n2011-08-29 00:59:09 ERROR Zope.SiteErrorLog 1314572349.670.543319514767 http://www.danieltordable.es/danieltordable.es\nTraceback (innermost last):\n  Module ZPublisher.Publish, line 115, in publish\n  Module ZPublisher.BaseRequest, line 437, in traverse\n  Module ZPublisher.BeforeTraverse, line 97, in __call__\n  Module Products.CMFCore.PortalObject, line 78, in __before_publishing_traverse__\n  Module zope.event, line 23, in notify\n  Module zope.component.event, line 24, in dispatch\n  Module zope.component._api, line 136, in subscribers\n  Module zope.component.registry, line 321, in subscribers\n  Module zope.interface.adapter, line 583, in subscribers\n  Module zope.component.event, line 32, in objectEventNotify\n  Module zope.component._api, line 136, in subscribers\n  Module zope.component.registry, line 321, in subscribers\n  Module zope.interface.adapter, line 583, in subscribers\n  Module plone.browserlayer.layer, line 15, in mark_layer\n  Module zope.component._api, line 179, in getAllUtilitiesRegisteredFor\n  Module zope.component.registry, line 176, in getAllUtilitiesRegisteredFor\n  Module ZODB.Connection, line 860, in setstate\n  Module ZODB.Connection, line 914, in _setstate\n  Module ZODB.serialize, line 613, in setGhostState\n  Module zope.component.persistentregistry, line 40, in __setstate__\n  Module zope.interface.adapter, line 89, in _createLookup\n  Module zope.interface.adapter, line 437, in __init__\n  Module zope.interface.adapter, line 474, in init_extendors\n  Module zope.interface.adapter, line 478, in add_extendor\nAttributeError: type object \'IIntIds\' has no attribute \'__iro__\'\n2011-08-29 00:59:10 ERROR ZODB.Connection Couldn\'t load state for 0x06a9\nTraceback (most recent call last):\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 860, in setstate\n    self._setstate(obj)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/Connection.py&quot;, line 914, in _setstate\n    self._reader.setGhostState(obj, p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/ZODB3-3.10.3-py2.6-freebsd-8.2-RELEASE-i386.egg/ZODB/serialize.py&quot;, line 613, in setGhostState\n    obj.__setstate__(state)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.component-3.9.5-py2.6.egg/zope/component/persistentregistry.py&quot;, line 40, in __setstate__\n    self._createLookup()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 89, in _createLookup\n    self._v_lookup = self.LookupClass(self)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 437, in __init__\n    self.init_extendors()\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 474, in init_extendors\n    self.add_extendor(p)\n  File &quot;/home/danieltordable.es/buildout-cache/eggs/zope.interface-3.6.3-py2.6-freebsd-8.2-RELEASE-i386.egg/zope/interface/adapter.py&quot;, line 478, in add_extendor\n    for i in provided.__iro__:\nAttributeError: type object \'IIntIds\' has no attribute \'__iro__\'</code></pre></p> <p align="right"><span style="font-size: 60%">Add a code snippet to your website: <a href="https://www.paste.org" target="_blank">www.paste.org</a></span></p> </body> </html>'